version: "3"
services:
  exercise1:
    env_file:
      - .env
    build: .
    image: exercise1
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "${MESSAGEAPP_PORT}:${MESSAGEAPP_PORT}"
